### ISSUE TITLE
How to work with router?

### ISSUE THREAD

**Issue by darenju** [JakubMarkiewicz/reason-transition-group#1]
Hello,

I am trying to implement this bindings with a small application that leverages the `reason-react`’s router.

My main `App` component renders a links bar and then the content of the page, which I am trying to transition in & out. I have tried what follows:

```reason
let make = _children => {
  ...component,
  // other stuff not needed for example (routing etc)
  render: ({state}) => {
    <div className={Styles.app}>
      <div className={Styles.header}>
        {/* Links */}
      </div>

      <div className={Styles.content}>
        <CSSTransition
          _in=true
          unmountOnExit=true
          timeout={`int(300)}
          classNames={
            `obj(
              CSSTransition.classFull(
                ~enter=Styles.messageEnter,
                ~enterActive=Styles.messageEnterActive,
                ~exit=Styles.messageExit,
                ~exitActive=Styles.messageExitActive,
                (),
              ),
            )
          }
        >
          ...{_state =>
              switch (state.route) {
                | Home => <Home />
                | About => <About />
              }
            }
        </CSSTransition>
      </div>
    </div>
  }
};
```

However, there does not seem to be any effect (I used the same styles than on the `EXAMPLE.md` file.)

I think there is probably something to play with the `_in` prop on `CSSTransition`, but I don’t know how to handle it with the router part.

Help appreciated!

**Comment by JakubMarkiewicz** [comment]
Hey, did a quick check (note it's using next.js routing).
` _in ` prop should not be required when firing transition on route change, instead use ` <TransitionGroup> ` and add ` key ` to ` <CSSTransition> `

Pseudo example
```ocaml
<TransitionGroup>
 <CSSTransition
   key={location}
   unmountOnExit=true
   timeout={`int(300)}
   classNames={
            `obj(
              CSSTransition.classFull(
                ~enter=Styles.messageEnter,
                ~enterActive=Styles.messageEnterActive,
                ~exit=Styles.messageExit,
                ~exitActive=Styles.messageExitActive,
                (),
              ),
            )
          }
>
  ...{_state => switch(location) {
      | A => <A/>
      | B => <B/>
}}
 </CSSTransiton>
</TransitonGroup>
```

**Comment by darenju** [comment]
Hey, thanks for the answer. I'll try to make it work.

By the way, is support of JSX3 scheduled? They've changed the way you declare ReasonReact components.

**Comment by JakubMarkiewicz** [comment]
@darenju 
I know, I've been planning to do so, it will be shipped today most likely. I will tag you here when it's ready :)

**Comment by JakubMarkiewicz** [comment]
@darenju 
jsx3 is live on @2.0.0

**Comment by darenju** [comment]
Nice! Thank you for your work.
